_windows_test: &windows_test
  language: sh
  os: windows
  before_install:
    - choco install php --version $PHP_INSTALL_VERSION --package-parameters='"/InstallDir:C:\php"'
    # Enable required extensions
    - sed -i 's/;extension=openssl/extension=openssl/g' /c/php/php.ini
    - sed -i 's/;extension=sockets/extension=sockets/g' /c/php/php.ini
    - sed -i 's/;extension=json/extension=json/g' /c/php/php.ini
    - sed -i 's/;extension=curl/extension=curl/g' /c/php/php.ini
    # Fetch composer
    - wget http://getcomposer.org/composer.phar
    # Install dependencies
    - php composer.phar install

matrix:
  include:
    - language: php
      dist: trusty
      php:
        - 5.4
        - 5.5
        - 5.6
        - 7.0
        - 7.1
        - 7.2
        - 7.3
        - nightly
    - name: "Windows PHP 5.4"
      env: PHP_INSTALL_VERSION=5.4.45
      <<: *windows_test
    - name: "Windows PHP 5.5"
      env: PHP_INSTALL_VERSION=5.5.38
      <<: *windows_test
    - name: "Windows PHP 5.6"
      env: PHP_INSTALL_VERSION=5.6.40
      <<: *windows_test
    - name: "Windows PHP 7.0"
      env: PHP_INSTALL_VERSION=7.0.33
      <<: *windows_test
    - name: "Windows PHP 7.1"
      env: PHP_INSTALL_VERSION=7.1.33
      <<: *windows_test
    - name: "Windows PHP 7.2"
      env: PHP_INSTALL_VERSION=7.2.30
      <<: *windows_test
    - name: "Windows PHP 7.3"
      env: PHP_INSTALL_VERSION=7.3.17
      <<: *windows_test
    - name: "Windows PHP 7.4"
      env: PHP_INSTALL_VERSION=7.4.5
      <<: *windows_test
  allow_failures:
    - php: nightly

install: composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover