language: php
sudo: false

_prepare_windows: &prepare_windows
  before_script:
    - choco install php --version $PHP_VERSION --package-parameters='"/InstallDir:C:\php"'
    # Export windows path into unix path
    - export PATH=/c/php:$PATH
    - sed -i 's/;extension=openssl/extension=openssl/g' /c/php/php.ini
    - sed -i 's/;extension=sockets/extension=sockets/g' /c/php/php.ini
    - sed -i 's/;extension=json/extension=json/g' /c/php/php.ini
    - sed -i 's/;extension=curl/extension=curl/g' /c/php/php.ini
    # Fetch composer
    - wget http://getcomposer.org/composer.phar
    # Install dependencies
    - php composer.phar install


matrix:
  include:
    - language: php
      install: composer install
      php:
        - 5.4
        - 5.5
        - 5.6
        - 7.0
        - 7.1
        - 7.2
        - nightly
        - hhvm

    - name: "Windows PHP 7.2"
      language: sh
      os: windows
      env:
        - PHP_VERSION=7.2.30
      <<: *prepare_windows
    - name: "Windows PHP 7.3"
      language: sh
      os: windows
      env:
        - PHP_VERSION=7.3.17
      <<: *prepare_windows
    - name: "Windows PHP 7.4"
      language: sh
      os: windows
      env:
        - PHP_VERSION=7.4.5
      <<: *prepare_windows
  allow_failures:
    - php: nightly
    - php: hhvm

script: vendor/bin/phpunit --coverage-clover=coverage.clover
