language: php
sudo: false

matrix:
  include:
    - language: php
      install: composer install
      php:
        - 5.4
        - 5.5
        - 5.6
        - 7.0
        - 7.1
        - 7.2
        - nightly
        - hhvm
    - name: "Windows Test"
      language: sh
      os: windows
      before_script:
        # Use chocolatey to install certain php version
        # Skipp --version to install latest stable release
        - choco install php --version 7.2.15 --package-parameters='"/InstallDir:C:\php"'
        # Export windows path into unix path
        - export PATH=/c/php:$PATH
        # Enable openssl used by composer
        - sed -i 's/;extension=openssl/extension=openssl/g' /c/php/php.ini
        # Enable mbstring used by phpunit
        - sed -i 's/;extension=mbstring/extension=mbstring/g' /c/php/php.ini
        #
        # You might want to enable other extensions as needed ...
        #
        # Fetch composer
        - wget http://getcomposer.org/composer.phar
        # Install dependencies
        - php composer.phar install
  allow_failures:
    - php: nightly
    - php: hhvm

script: vendor/bin/phpunit --coverage-clover=coverage.clover
